CREATE TABLE BIQuery (
 ID CHAR(10) NOT NULL,
 Query VARCHAR(400)
);

ALTER TABLE BIQuery ADD CONSTRAINT PK_BIQuery PRIMARY KEY (ID);


CREATE TABLE LayerAnswer (
 LA_ID VARCHAR(60) NOT NULL,
 Answer VARCHAR(500)
);

ALTER TABLE LayerAnswer ADD CONSTRAINT PK_LayerAnswer PRIMARY KEY (LA_ID);


CREATE TABLE LayerCategory (
 CategoryID VARCHAR(60) NOT NULL,
 CategoryName VARCHAR(50)
);

ALTER TABLE LayerCategory ADD CONSTRAINT PK_LayerCategory PRIMARY KEY (CategoryID);


CREATE TABLE LQuestion (
 LQ_ID VARCHAR(60) NOT NULL,
 QuestionText VARCHAR(500)
);

ALTER TABLE LQuestion ADD CONSTRAINT PK_LQuestion PRIMARY KEY (LQ_ID);


CREATE TABLE Person (
 PersonID VARCHAR(60) NOT NULL
);

ALTER TABLE Person ADD CONSTRAINT PK_Person PRIMARY KEY (PersonID);


CREATE TABLE SGAnswer (
 SGA_ID VARCHAR(60) NOT NULL,
 Answer VARCHAR(500)
);

ALTER TABLE SGAnswer ADD CONSTRAINT PK_SGAnswer PRIMARY KEY (SGA_ID);


CREATE TABLE SGDimension (
 SGD_ID VARCHAR(60) NOT NULL,
 DimensionName VARCHAR(30)
);

ALTER TABLE SGDimension ADD CONSTRAINT PK_SGDimension PRIMARY KEY (SGD_ID);


CREATE TABLE SGQuestion (
 SGQ_ID VARCHAR(60) NOT NULL,
 SGD_ID VARCHAR(60) NOT NULL,
 QuestionText VARCHAR(500)
);

ALTER TABLE SGQuestion ADD CONSTRAINT PK_SGQuestion PRIMARY KEY (SGQ_ID);


CREATE TABLE Survey (
 SurveyID VARCHAR(60) NOT NULL
);

ALTER TABLE Survey ADD CONSTRAINT PK_Survey PRIMARY KEY (SurveyID);


CREATE TABLE fact_L_AtoQ (
 LQ_ID VARCHAR(60) NOT NULL,
 LA_ID VARCHAR(60) NOT NULL
);

ALTER TABLE fact_L_AtoQ ADD CONSTRAINT PK_fact_L_AtoQ PRIMARY KEY (LQ_ID,LA_ID);


CREATE TABLE fact_LQuestionInCat (
 CategoryID VARCHAR(60) NOT NULL,
 LQ_ID VARCHAR(60) NOT NULL
);

ALTER TABLE fact_LQuestionInCat ADD CONSTRAINT PK_fact_LQuestionInCat PRIMARY KEY (CategoryID,LQ_ID);


CREATE TABLE fact_SGA_AtoQ (
 SGA_ID VARCHAR(60) NOT NULL,
 SGQ_ID VARCHAR(60) NOT NULL
);

ALTER TABLE fact_SGA_AtoQ ADD CONSTRAINT PK_fact_SGA_AtoQ PRIMARY KEY (SGA_ID,SGQ_ID);


CREATE TABLE fact_SurveyInstance (
 PersonID VARCHAR(60) NOT NULL,
 SurveyID VARCHAR(60) NOT NULL,
 SurveyInstanceID VARCHAR(60) NOT NULL
);

ALTER TABLE fact_SurveyInstance ADD CONSTRAINT PK_fact_SurveyInstance PRIMARY KEY (PersonID,SurveyID,SurveyInstanceID);


CREATE TABLE LQInSurvey (
 SurveyID VARCHAR(60) NOT NULL,
 LQ_ID VARCHAR(60) NOT NULL
);

ALTER TABLE LQInSurvey ADD CONSTRAINT PK_LQInSurvey PRIMARY KEY (SurveyID,LQ_ID);


CREATE TABLE SGQInSurvey (
 SurveyID VARCHAR(60) NOT NULL,
 SGQ_ID VARCHAR(60) NOT NULL
);

ALTER TABLE SGQInSurvey ADD CONSTRAINT PK_SGQInSurvey PRIMARY KEY (SurveyID,SGQ_ID);


CREATE TABLE fact_LResponse (
 LR_ID VARCHAR(60) NOT NULL,
 PersonID VARCHAR(60) NOT NULL,
 SurveyID VARCHAR(60) NOT NULL,
 SurveyInstanceID VARCHAR(60) NOT NULL,
 LQ_ID VARCHAR(60) NOT NULL,
 LA_ID VARCHAR(60) NOT NULL
);

ALTER TABLE fact_LResponse ADD CONSTRAINT PK_fact_LResponse PRIMARY KEY (LR_ID,PersonID,SurveyID,SurveyInstanceID);


CREATE TABLE fact_SGResponse (
 SGR_ID VARCHAR(60) NOT NULL,
 PersonID VARCHAR(60) NOT NULL,
 SurveyID VARCHAR(60) NOT NULL,
 SurveyInstanceID VARCHAR(60) NOT NULL,
 SGQ_ID VARCHAR(60),
 SGA_ID VARCHAR(60) NOT NULL
);

ALTER TABLE fact_SGResponse ADD CONSTRAINT PK_fact_SGResponse PRIMARY KEY (SGR_ID,PersonID,SurveyID,SurveyInstanceID);


ALTER TABLE SGQuestion ADD CONSTRAINT FK_SGQuestion_0 FOREIGN KEY (SGD_ID) REFERENCES SGDimension (SGD_ID);


ALTER TABLE fact_L_AtoQ ADD CONSTRAINT FK_fact_L_AtoQ_0 FOREIGN KEY (LQ_ID) REFERENCES LQuestion (LQ_ID);
ALTER TABLE fact_L_AtoQ ADD CONSTRAINT FK_fact_L_AtoQ_1 FOREIGN KEY (LA_ID) REFERENCES LayerAnswer (LA_ID);


ALTER TABLE fact_LQuestionInCat ADD CONSTRAINT FK_fact_LQuestionInCat_0 FOREIGN KEY (CategoryID) REFERENCES LayerCategory (CategoryID);
ALTER TABLE fact_LQuestionInCat ADD CONSTRAINT FK_fact_LQuestionInCat_1 FOREIGN KEY (LQ_ID) REFERENCES LQuestion (LQ_ID);


ALTER TABLE fact_SGA_AtoQ ADD CONSTRAINT FK_fact_SGA_AtoQ_0 FOREIGN KEY (SGA_ID) REFERENCES SGAnswer (SGA_ID);
ALTER TABLE fact_SGA_AtoQ ADD CONSTRAINT FK_fact_SGA_AtoQ_1 FOREIGN KEY (SGQ_ID) REFERENCES SGQuestion (SGQ_ID);


ALTER TABLE fact_SurveyInstance ADD CONSTRAINT FK_fact_SurveyInstance_0 FOREIGN KEY (PersonID) REFERENCES Person (PersonID);
ALTER TABLE fact_SurveyInstance ADD CONSTRAINT FK_fact_SurveyInstance_1 FOREIGN KEY (SurveyID) REFERENCES Survey (SurveyID);


ALTER TABLE LQInSurvey ADD CONSTRAINT FK_LQInSurvey_0 FOREIGN KEY (SurveyID) REFERENCES Survey (SurveyID);
ALTER TABLE LQInSurvey ADD CONSTRAINT FK_LQInSurvey_1 FOREIGN KEY (LQ_ID) REFERENCES LQuestion (LQ_ID);


ALTER TABLE SGQInSurvey ADD CONSTRAINT FK_SGQInSurvey_0 FOREIGN KEY (SurveyID) REFERENCES Survey (SurveyID);
ALTER TABLE SGQInSurvey ADD CONSTRAINT FK_SGQInSurvey_1 FOREIGN KEY (SGQ_ID) REFERENCES SGQuestion (SGQ_ID);


ALTER TABLE fact_LResponse ADD CONSTRAINT FK_fact_LResponse_0 FOREIGN KEY (PersonID,SurveyID,SurveyInstanceID) REFERENCES fact_SurveyInstance (PersonID,SurveyID,SurveyInstanceID);
ALTER TABLE fact_LResponse ADD CONSTRAINT FK_fact_LResponse_1 FOREIGN KEY (LQ_ID) REFERENCES LQuestion (LQ_ID);
ALTER TABLE fact_LResponse ADD CONSTRAINT FK_fact_LResponse_2 FOREIGN KEY (LA_ID) REFERENCES LayerAnswer (LA_ID);


ALTER TABLE fact_SGResponse ADD CONSTRAINT FK_fact_SGResponse_0 FOREIGN KEY (PersonID,SurveyID,SurveyInstanceID) REFERENCES fact_SurveyInstance (PersonID,SurveyID,SurveyInstanceID);
ALTER TABLE fact_SGResponse ADD CONSTRAINT FK_fact_SGResponse_1 FOREIGN KEY (SGQ_ID) REFERENCES SGQuestion (SGQ_ID);
ALTER TABLE fact_SGResponse ADD CONSTRAINT FK_fact_SGResponse_2 FOREIGN KEY (SGA_ID) REFERENCES SGAnswer (SGA_ID);




/*
DROP TABLE BIQuery CASCADE CONSTRAINTS;
DROP TABLE LayerAnswer CASCADE CONSTRAINTS;
DROP TABLE LayerCategory CASCADE CONSTRAINTS;
DROP TABLE LQuestion CASCADE CONSTRAINTS;
DROP TABLE Person CASCADE CONSTRAINTS;
DROP TABLE SGAnswer CASCADE CONSTRAINTS;
DROP TABLE SGDimension CASCADE CONSTRAINTS;
DROP TABLE SGQuestion CASCADE CONSTRAINTS;
DROP TABLE Survey CASCADE CONSTRAINTS;
DROP TABLE fact_L_AtoQ CASCADE CONSTRAINTS;
DROP TABLE fact_LQuestionInCat CASCADE CONSTRAINTS;
DROP TABLE fact_SGA_AtoQ CASCADE CONSTRAINTS;
DROP TABLE fact_SurveyInstance CASCADE CONSTRAINTS;
DROP TABLE LQInSurvey CASCADE CONSTRAINTS;
DROP TABLE SGQInSurvey CASCADE CONSTRAINTS;
DROP TABLE fact_LResponse CASCADE CONSTRAINTS;
DROP TABLE fact_SGResponse CASCADE CONSTRAINTS;*/
